CREATE TABLE uzytkowniczy {
    id INT AUTO-INCREMENT PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
}

CREATE TABLE maszyny {
    id INT AUTO-INCREMENT PRIMARY KEY,
    id_uzytkownika INT NOT NULL,
    nazwaMaszyny VARCHAR(50) NOT NULL,
}
